sudo: required

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y openssh-client shellcheck
  - sudo apt-get install -y python3 python3-pip python3-setuptools
  - sudo rm /usr/local/bin/pip
  - sudo ln -s ../../bin/python3 /usr/local/bin/python
  - sudo ln -s ../../bin/pip3 /usr/local/bin/pip
  - sudo pip install pre-commit

script:
  - pre-commit run --all-files
  - export PATH="$(pwd)/bin:$PATH"
  - docker build -t nyag/dumpling dumpling
  - dumpling-test
