#!/bin/bash
set -eux

# Step 1 - Prepare the dough for the dumpling.

# Set timezone to America/New_York.
ln -sf /usr/share/zoneinfo/America/New_York /etc/localtime

# Install Python development tools, compilers, and build dependencies.
# apt-transport-https is needed for installing nodejs.
# bzip2, tar, wget are needed to download phantomjs.
# default-jre needed for Tabula.
# git is needed to download oaglib.
# gnupg is needed to authenticate the install of nodejs.
# graphviz is needed for dask.dataframe.DataFrame.visualize
# locales is needed to allow for installing Python packages that use unicode
# characters.
# lsb-release is used with nodejs to determine what distro release we're using.
# proj-bin is needed for pyproj.
# unixodbc-dev is needed to build pyodbc.
# GDAL depends on specific versions of its C/C++ libraries, so just
# install the Debian package instead of building from source.

apt-get -qq update
apt-get install -qy --no-install-recommends \
   apt-transport-https \
   bzip2 \
   default-jre \
   g++ \
   gcc \
   git \
   gnupg \
   graphviz \
   libffi-dev \
   locales \
   lsb-release \
   proj-bin \
   python3-dev \
   python3-gdal \
   python3-pip \
   python3-venv \
   python3-wheel \
   tar \
   unixodbc-dev \
   virtualenv \
   wget

# Set locale to en-US UTF-8
locale-gen en_US.UTF-8
# sets new locale in dpkg to en-US UTF-8 and makes it default
printf "152\n3" | dpkg-reconfigure locales
update-locale LANG=en_US.UTF-8
export LANG=en_US.UTF-8

# Install NodeJS for use with Jupyter.
wget --quiet -O - https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
wget --quiet -O - https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
# update as stable node version changes
# TODO: potentially automate this?
VERSION=node_12.x
DISTRO="$(lsb_release -s -c)"
echo "deb https://deb.nodesource.com/$VERSION $DISTRO main" | tee /etc/apt/sources.list.d/nodesource.list
echo "deb-src https://deb.nodesource.com/$VERSION $DISTRO main" | tee -a /etc/apt/sources.list.d/nodesource.list
echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee -a /etc/apt/sources.list.d/nodesource.list
apt-get update
apt-get install -qy --no-install-recommends nodejs yarn

# Create a symlink from python/pip to Python 3,
# since we are not using Python 2.
ln -s ../../bin/python3 /usr/local/bin/python
ln -s ../../bin/pip3 /usr/local/bin/pip

# Python 3.8 needed for black.
apt-get install -qy --no-install-recommends \
    make \
    build-essential \
    libbz2-dev \
    libc6-dev \
    libgdbm-dev \
    libreadline-gplv2-dev \
    libncurses5-dev \
    libncursesw5-dev \
    libsqlite3-dev \
    libssl-dev \
    llvm \
    tk-dev \
    xz-utils \
    zlib1g-dev
# Build and install python3.8, then pip install black in 3.8.
wget -qO /tmp/Python-3.8.0.tgz https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tgz
cd /tmp
tar xvf Python-3.8.0.tgz
cd Python-3.8.0
./configure --enable-optimizations
make -j8
make altinstall
pip3.8 install black

# Step 2 - Pack the dumpling with lots of veggies and steam it.
# Install Python packages for data science.
# setuptools needs to be installed first for cython.
# Cython needs to be installed first for fastparquet, used by dask.
# We can remove fastparquet once dask fully supports pyarrow.
grep -v "#" /srv/dumpling_packages.txt > /srv/tmp.txt
mv /srv/tmp.txt /srv/dumpling_packages.txt
pip3 install --no-cache-dir setuptools
pip3 install --no-cache-dir cython
pip3 install --no-cache-dir -r /srv/dumpling_packages.txt

export NODE_OPTIONS=--max-old-space-size=4096
# TODO: requirements.txt for labextension?
jupyter labextension install @jupyter-widgets/jupyterlab-manager@1.1 --no-build
jupyter labextension install jupyterlab-plotly@1.5.0 --no-build
jupyter labextension install plotlywidget@1.5.0 --no-build
jupyter labextension install @jupyterlab/toc
jupyter lab build
unset NODE_OPTIONS

# Install PhantomJS as a Selenium WebDriver.
# TODO: automatically find the latest version of PhantomJS.
# It would be nice to use the Debian package but there are bugs:
# https://bugs.debian.org/cgi-bin/pkgreport.cgi?package=phantomjs
wget --no-verbose --no-hsts -O phantomjs.tar.bz2 \
    https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
tar --wildcards --strip-components=2 -xf phantomjs.tar.bz2 \
    'phantomjs*/bin/phantomjs'
mv phantomjs /usr/local/bin
rm phantomjs.tar.bz2

# Step 3 - Add some dipping sauce to the dumpling.
# Install Debian packages for convenient CLI work.
# bash-completion, cowsay, fortune* are used in bashrc.
# cifs-utils, gosu are used in docker-entrypoint.
# locales is needed to support UTF-8 locale, which is required by tmux.
apt-get install -qy --no-install-recommends \
   bash-completion \
   bc \
   cifs-utils \
   cookiecutter \
   cowsay \
   curl \
   dnsutils \
   fortune-mod \
   fortunes \
   fortunes-bofh-excuses \
   ghostscript \
   gosu \
   host \
   htop \
   imagemagick \
   jq \
   less \
   locales \
   lsof \
   man-db \
   nano \
   net-tools \
   openssh-client \
   p7zip-full \
   postgresql-client \
   procps \
   shellcheck \
   sudo \
   tree \
   tmux \
   unzip \
   vim \
   watch

# Step 4 - Indulge in the dumpling.
# Enable sudo without a password.
echo '%sudo ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/nopasswd

# Modify bashrc to enable bash-completion and other savories.
# Enable git pull rebase autostash.
# Configure Jupyter Notebook port.
echo '. /srv/bashrc' >> /etc/bash.bashrc
echo '. /srv/bash_logout' >> /etc/bash.bash.logout
ln -s /srv/gitconfig /etc/.
mkdir /etc/jupyter
ln -s /srv/jupyter_notebook_config.py /etc/jupyter/.

# Default to UTF-8 locale.
echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen
locale-gen
update-locale LANG=en_US.UTF-8

# Step 5 - Clean the dishes.
apt-get clean
rm -rf /var/lib/apt/lists/*
